apiVersion: v1
kind: Template
labels:
  template: birthday-paradox-build
metadata:
  name: birthday-paradox-build
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:${IMAGE_TAG}
    source:
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: java:latest
          namespace: openshift
      type: Source
parameters:
- name: APPLICATION_NAME
  required: true
- name: IMAGE_TAG
  required: true
- name: APPLICATION_CONTEXT_DIR
  value: birthday-paradox
